language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.2
      env: TYPO3_VERSION=^8 COVERAGE=1

env:
  global:
    secure: S8QheEMVpSRsPPIhYQZ4tUCTbxpM7csZ0GydJaPY8p/FAEnZLiH6xcsiTGKOljva5HDelCdBvunaWtUO/+CdKIgsdbQGbqc1aWmG6gr+ShQk4X3KzeAA91AFmkJOR6Jv69lUTm6Uo9AKs1JtuVZsOa1aoOmfApohqFuXsRBNXlg=

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
- >
  if [[ "$COVERAGE" != "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  fi

- >
  if [[ "$COVERAGE" == "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml Tests/Unit/ --coverage-clover .Build/log/coverage/clover.xml
  fi

after_success:
- >
  if [[ "$COVERAGE" == "1" ]]; then
    bash <(curl -s https://codecov.io/bash) -B $TRAVIS_BRANCH
  fi
